version: '3'

services:

    gateway:
        image: gateway:latest
        ports:
          - '80:80'
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    baseweb:
        container_name: baseweb
        image: baseweb:latest
        environment:
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          REDIS_HOST: redis
          REDIS_PORT: 6379
          MONGO_URI: 'mongodb:27017'
          MONGO_DB_NAME: baseweb
          POSTGRES_DB: ${PG_DATABASE:-dms}
          POSTGRES_PASSWORD: ${PG_PASSWORD:-root}
          POSTGRES_USER: postgres
          GOOGLE_MAP_API_KEY: ''
          CONTENT_SERVICE_HOST: content-service
          CONTENT_SERVICE_PORT: 8081
        volumes:
          - baseweb_data:/app/data_upload
     basewebfrontend:
        image: basewebfrontend:latest

    redis:
        image: "redis:alpine"

    db:
        image: postgres
        environment:
          POSTGRES_DB: ${PG_DATABASE:-dms}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${PG_PASSWORD:-root}
        volumes:
          - pg_data:/var/lib/postgresql/data

    mongodb:
        image: mongo:latest
        command:
          - --replSet=rs0
        volumes:
          - mongo_data:/var/lib/mongodb/data

volumes:
  mongo_data:
    driver: local
  pg_data:
    driver: local
  baseweb_data:
    driver: local
