version: "3.5"

services:
  mongo_one:
    container_name: mongo1
    image: mongo #should specify version mongo herei
    ports:
        - "27017:27017"
    command: mongod --replSet my-mongo-set

  mongo_two:
    container_name: mongo2
    image: mongo #should specify version mongo here
    ports:
        - "27018:27017"
    command: mongod --replSet my-mongo-set

  mongo_three:
    container_name: mongo3
    image: mongo #should specify version mongo here
    ports:
        - "27019:27017"
    command: mongod --replSet my-mongo-set

networks:
  default:
    external:
      name: my-mongo-cluster
